import { Router } from "express";
import { databaseMode, query } from "../config/db.js";
import { requireAuth } from "../middleware/auth.js";

const router = Router();
router.use(requireAuth);
router.post("/reports", async (request, response, next) => { try { const reason = String(request.body?.reason || "").trim().slice(0, 120); const details = String(request.body?.details || "").trim().slice(0, 2000); const reportedUserId = Number(request.body?.reportedUserId) || null; if (!reason) return response.status(400).json({ message: "A report reason is required." }); if (databaseMode === "preview") return response.status(201).json({ id: Date.now(), reason, status: "submitted" }); const result = await query("INSERT INTO safety_reports (reporter_id, reported_user_id, reason, details) VALUES (?, ?, ?, ?)", [request.user.id, reportedUserId, reason, details]); return response.status(201).json({ id: result.insertId, reason, status: "submitted" }); } catch (error) { return next(error); } });
router.post("/blocks/:userId", async (request, response, next) => { try { const blockedUserId = Number(request.params.userId); if (!Number.isSafeInteger(blockedUserId) || blockedUserId < 1) return response.status(400).json({ message: "Invalid member." }); if (databaseMode === "mysql") await query("INSERT IGNORE INTO blocks (blocker_id, blocked_user_id) VALUES (?, ?)", [request.user.id, blockedUserId]); return response.status(201).json({ blockedUserId, status: "blocked" }); } catch (error) { return next(error); } });
router.delete("/blocks/:userId", async (request, response, next) => { try { const blockedUserId = Number(request.params.userId); if (!Number.isSafeInteger(blockedUserId) || blockedUserId < 1) return response.status(400).json({ message: "Invalid member." }); if (databaseMode === "mysql") await query("DELETE FROM blocks WHERE blocker_id=? AND blocked_user_id=?", [request.user.id, blockedUserId]); return response.json({ blockedUserId, status: "unblocked" }); } catch (error) { return next(error); } });
router.post("/account-deletion", async (request, response, next) => { try { const reason=String(request.body?.reason||"").trim().slice(0,500); if(databaseMode==="preview")return response.status(202).json({status:"preview",message:"Deletion confirmation is demonstrated without deleting preview data."}); await query("INSERT INTO account_deletion_requests (user_id,reason,status) VALUES (?,?,'requested') ON DUPLICATE KEY UPDATE reason=VALUES(reason),status='requested',requested_at=NOW()",[request.user.id,reason]); return response.status(202).json({status:"requested"}); } catch(error){ return next(error); } });
export default router;
